apiVersion: apps/v1
kind: Deployment
metadata:
  name:  spring-boot-app
  namespace: default
  labels:
    app:  spring-boot-app
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  replicas: 3
  template:
    metadata:
      labels:
        app:  spring-boot-app
    spec:
      containers:
      - name:  spring-boot-app
        image:  shubham1807/springbootapp:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: dbname
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        ports:
        - containerPort:  8080
      restartPolicy: Always