apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
spec:
  selector:
    matchLabels:
      app: bookstore
  replicas: 3
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore
          image: shubham1807/book-store:1.0
          ports:
            - containerPort: 8080
          env:   
            - name: DB_HOST   
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME  
              valueFrom :
                configMapKeyRef:
                  name: db-config
                  key: dbname
            - name: DB_USERNAME  
              valueFrom :
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: DB_PASSWORD 
              valueFrom :
                secretKeyRef:
                  name: mysql-secrets
                  key: password
