apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3600
          env:
           - name: MYSQL_USER
             valueFrom:
               secretKeyRef:
                 name: mysql-secrets
                 key: username
           - name: MYSQL_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mysql-secrets
                 key: password
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mysqldb
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: mysql-pv-claim