name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag book-store:$(date +%s)
    - name: Run the MySQL Docker image
      run: docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root 
    - name: Run the Docker image
      run: docker run -d -p 8080:8080 --name bookStore book-store:$(date +%s)
