name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag book-store:$(date +%s)
    - name: login Docker-hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
    - name: Tag the Docker image
      run: docker tag book-store:$(date +%s) shubham1807/book-store:latest
    - name: Push Docker image to Docker Hub
      run: docker push shubham1807/book-store:latest
    - name: Apply Kubernetes manifests
      run: kubectl apply -f /kubernetes


      
