name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag book-store:latest
    - name: login Docker-hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
    - name: Tag the Docker image
      run: docker tag book-store:latest ${{ secrets.DOCKER_USERNAME }}/book-store:latest
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/book-store:latest
    - name: run MySQL COntainer
      run: docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=bookstore --name mysql mysql:latest
    - name: run APP COntainer
      run: docker run -d -p 8080:8080 --name bookstore book-store:latest
    - name: run APP COntainer
      run: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' bookstore



      
